# Generated by Django 3.2.9 on 2024-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Taiwanese Recipes', 'Taiwanese Recipes'), ('Szechuan Recipes', 'Szechuan Recipes'), ('Indian Recipes', 'Indian Recipes'), ('Thai Recipes', 'Thai Recipes'), ('Korean Recipes', 'Korean Recipes'), ('Cantonese Recipes', 'Cantonese Recipes'), ('Japanese Recipes', 'Japanese Recipes')], max_length=50)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('procedure', models.TextField()),
                ('prep_time', models.DurationField()),
                ('cook_time', models.DurationField()),
                ('servings', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
