# Generated by Django 3.2.9 on 2024-07-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='cook_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='prep_time',
            field=models.CharField(max_length=50),
        ),
    ]
