# Generated by Django 3.2.9 on 2024-07-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20240714_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='servings',
        ),
    ]
