# Generated by Django 3.2.9 on 2024-07-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='recipeImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
