# Generated by Django 3.2.9 on 2024-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_recipemodel_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='recipeImage',
            field=models.TextField(blank=True),
        ),
    ]
