# Generated by Django 3.2.9 on 2024-07-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipemodel_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='category',
            field=models.CharField(blank=True, choices=[('Taiwanese Recipe', 'Taiwanese Recipe'), ('Szechuan Recipe', 'Szechuan Recipe'), ('Indian Recipe', 'Indian Recipe'), ('Thai Recipe', 'Thai Recipe'), ('Korean Recipe', 'Korean Recipe'), ('Cantonese Recipe', 'Cantonese Recipe'), ('Japanese Recipe', 'Japanese Recipe')], max_length=50),
        ),
    ]
